In [43]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder,LabelEncoder,StandardScaler
import pickle
from sklearn.model_selection import train_test_split
import datetime

In [44]:
data=pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [45]:
data=data.drop(["RowNumber","CustomerId","Surname"],axis=1)

In [46]:
one_hot_encoder_ge = OneHotEncoder()
encoder_ge = one_hot_encoder_ge.fit_transform(data[["Geography"]]).toarray()
encoder_ge

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [47]:
one_hot_encoder_ge.get_feature_names_out()

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [48]:
geo_encoded_df= pd.DataFrame(encoder_ge,columns=one_hot_encoder_ge.get_feature_names_out())
geo_encoded_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [49]:
data=pd.concat([data.drop(["Geography"],axis=1),geo_encoded_df],axis=1)

In [50]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,Female,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,Female,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,Female,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,Female,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,Female,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [51]:
encoder_ge =LabelEncoder()
data["Gender"]=encoder_ge.fit_transform(data["Gender"])
data.tail()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [52]:
with open("enocder_ge.pkl","wb")as file:
    pickle.dump(encoder_ge,file)

In [53]:
with open("one_hot_enocder_ge.pkl","wb") as file:
    pickle.dump(one_hot_encoder_ge,file)

In [54]:
#existed is target prediction

In [13]:
x=data.drop(["Exited"],axis=1)
x

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,1.0,0.0,0.0

In [14]:
y=data["Exited"]
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [15]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=98)

In [16]:
x_train.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
2704,718,1,27,2,0.00,2,0,0,26229.24,1.0,0.0,0.0
349,582,1,39,5,0.00,2,1,1,129892.93,1.0,0.0,0.0
739,692,0,28,8,95059.02,2,1,0,44420.18,1.0,0.0,0.0
3349,665,0,45,5,155447.65,2,1,0,51871.95,0.0,1.0,0.0
7837,850,1,48,2,0.00,1,1,0,169425.30,0.0,0.0,1.0

In [17]:
scaler=StandardScaler()

In [18]:
x_train= scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[ 0.69053986,  0.91358523, -1.13950578, ...,  0.98754423,
        -0.57406576, -0.57098639],
       [-0.71442425,  0.91358523,  0.00464015, ...,  0.98754423,
        -0.57406576, -0.57098639],
       [ 0.42194378, -1.09458863, -1.04416029, ...,  0.98754423,
        -0.57406576, -0.57098639],
       ...,
       [-0.10491776,  0.91358523, -0.7581238 , ...,  0.98754423,
        -0.57406576, -0.57098639],
       [ 0.09136399,  0.91358523, -0.47208732, ...,  0.98754423,
        -0.57406576, -0.57098639],
       [ 1.65128737,  0.91358523,  0.09998564, ...,  0.98754423,
        -0.57406576, -0.57098639]], shape=(7500, 12))

In [19]:
with open ("scaler.pkl","wb") as file:
    pickle.dump(scaler,file)

In [20]:
x_train.shape[0]

7500

In [21]:
x_train.shape[1]

12

### ANN IMPLENTATION

In [22]:
import tensorflow as tf

print("TensorFlow:", tf.__version__)
print("GPU:", tf.config.list_physical_devices("GPU"))

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1787780403.359592    2803 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1787780403.417868    2803 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1787780405.457658    2803 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

TensorFlow: 2.21.0
GPU: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [23]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Input
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

## Build ANN Model

In [24]:
model = Sequential([
    Input(shape=(x_train.shape[1],)),
    Dense(64,activation="relu"),
    Dense(32,activation="relu"),
    Dense(1,activation="sigmoid")
]
                  )

I0000 00:00:1787780408.305710    2803 gpu_device.cc:2043] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1767 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3050 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6

In [25]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [26]:
opt = tf.keras.optimizers.Adam(learning_rate=0.1)
loss = tf.keras.losses.BinaryCrossentropy()
loss

## compile model

In [27]:
model.compile(optimizer=opt,loss="binary_crossentropy",metrics=["accuracy"])

#### setup tensorboards

In [28]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
log_dir = "logs/fit/" +datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir= log_dir,histogram_freq=1)

#### early stopping

In [29]:
early_stopping_callbacks = EarlyStopping(monitor='val_loss',patience=3,restore_best_weights=True)

In [34]:
history=model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=150,callbacks = [tensorflow_callback,early_stopping_callbacks])

Epoch 1/150
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7961 - loss: 0.5053 - val_accuracy: 0.7952 - val_loss: 0.5072
Epoch 2/150
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7961 - loss: 0.5045 - val_accuracy: 0.7952 - val_loss: 0.5054
Epoch 3/150
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7967 - loss: 0.5048 - val_accuracy: 0.7952 - val_loss: 0.5069
Epoch 4/150
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7967 - loss: 0.5049 - val_accuracy: 0.7952 - val_loss: 0.5297
Epoch 5/150
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7967 - loss: 0.5078 - val_accuracy: 0.7952 - val_loss: 0.5076

In [37]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [38]:
%load_ext tensorboard

In [39]:
%tensorboard --logdir logs/fit